name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DESTINATION_DIR: "~/services/cross-chain-meme-creator-backend"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Create new directory & copy files
      run: |
        mkdir -p $DESTINATION_DIR
        cp -r . $DESTINATION_DIR
        
    - name: Install dependencies & build
      run: | 
        cd $DESTINATION_DIR
        npm install
        npn run build
