name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DESTINATION_DIR: "/services/cross-chain-meme-creator-backend"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Install dependencies & build
      run: | 
        npm install
        npn run build

    - name: Create new directory & copy files
      run: |
        mkdir -p -r $DESTINATION_DIR
        mkdir -p  $DESTINATION_DIR/dist
        copy -r /dist  $DESTINATION_DIR/dist
